### PR TITLE
Windows: Implement Drop for GLContext

### LINKED ISSUE #8: Implement 'Drop' for GLContext on Windows
Implementation should go here: 
https://github.com/kettle11/kettlewin/blob/e0bb32b4e9083493bafcc53e5e97f00a24978536/gl_context/src/windows/mod.rs#L193

### PR DESCRIPTION
**Pull request by lunabunn**
Fix #8.

Questions:
Where should we `DeleteDC`?
Is it a good idea here to panic in the `Drop` impl?

### CODE REVIEW

**Comment by lunabunn** [comment]
Didn't mean to do that 😅

**Comment by kettle11** [comment]
Looks good!

As for `DeleteDC` that prompted me to look around a bit and I think the `set_window` could use improvements:

* If `None` is passed in then `ReleaseDC` seems like it should still be called, presently it's not.
* Also if `None` is passed in does `SetPixelFormat` just error?

It also seems like in your `Drop` implementation that if there's a current window and device context then `ReleaseDC` should be called.

**Comment by lunabunn** [comment]
Is there ever a current window but not a DC or vice versa?

**Comment by kettle11** [comment]
I was wondering that yesterday, and I don't think so. The Device Context (DC) is associated with a window. They could be coupled together as a tuple within an `Option` instead of separate options.

**Comment by lunabunn** [comment]
Here's DeleteDC added to the drop, for now.

**Comment by kettle11** [comment]
Cool. Is this ready to merge? We can fix-up the other things I mentioned later.

**Comment by lunabunn** [comment]
@kettle11 Sorry for the delay. Now it should be ready to merge!

**Pull request merged**
