### PR TITLE
Implement cursor functions for web

### LINKED ISSUE #5: Implement 'set_cursor' for Web
https://github.com/kettle11/kettlewin/blob/e0bb32b4e9083493bafcc53e5e97f00a24978536/platforms/web/src/application_web.rs#L39

`set_cursor` should change the cursor on the canvas for web.

The cursors from the cursor enum must be supported (or approximated with something comparable): https://github.com/kettle11/kettlewin/blob/6fb7ae5d463d8efb42a4cf164c685bd98ab41f01/platform_common/src/cursors.rs

### LINKED ISSUE #6: Implement 'hide_cursor' and 'show_cursor' for web
https://github.com/kettle11/kettlewin/blob/e0bb32b4e9083493bafcc53e5e97f00a24978536/platforms/web/src/application_web.rs#L42

### PR DESCRIPTION
**Pull request by lunabunn**
**UNTESTED!**

Fixes #5, fixes #6.
Might be worth noting that the implementation is not thread-safe.

### CODE REVIEW

**Comment by lunabunn** [comment]
Verified everything working as expected (in Chrome, version 87.0.4280.141).
Chrome has a weird bug where [if you have the developer console on, the cursor changes only take place when a mouse event is fired](https://stackoverflow.com/questions/1718415/getting-the-browser-cursor-from-wait-to-auto-without-the-user-moving-the-mou/37351569#37351569), but seems like a minor issue.
Code still isn't thread-safe. Does wasm support threads now?

**Comment by lunabunn** [comment]
As a sidenote, `Cursor::PointingHand => LoadCursorW(null_mut(), IDC_ARROW),` seems like a typo in the Windows implementation for `set_cursor`. Should be `IDC_HAND`.

**Comment by kettle11** [comment]
> Implementation still isn't thread-safe. Does wasm support threads now?

Browser callbacks always call into `kapp` on the main thread and `kapp's` `Application`, `EventLoop` and `Window` are `!Send`. 

So even if some other Wasm parts run on other threads (in web workers) it's fine if the `kapp` code is thread safe as it's only interacting directly with the main thread.

**Comment by kettle11** [comment]
Merged! Thanks for fixing up some of these missing parts. It's really appreciated! 👍

**Pull request merged**
